%% PN-Guidance-Interceptor-Missile-Simulation.m
%
% AUTO-BUILDS a nonlinear 6-DOF interceptor missile Simulink model.
%
% Run this whole script in MATLAB (tested against R2021b+ style APIs;
% should work on most modern releases). It will:
%   1. Create a new Simulink model "Interceptor6DOF"
%   2. Add subsystems: Target, Missile_NED_State, Guidance_PN, Autopilot,
%      Actuators, Aerodynamics, Missile_EOM + Integrator
%   3. Write the MATLAB Function block code for each subsystem
%   4. Wire everything into a closed guidance loop
%   5. Configure the solver and save as Interceptor6DOF.slx
%
% Physics reference frames / equations used:
%   - Body axes state vector: x = [u v w p q r phi theta psi xe ye ze]'
%   - NED (North-East-Down) inertial frame for position/target geometry
%   - Standard Newton-Euler 6DOF equations (Stevens & Lewis form)
%   - True Proportional Navigation guidance law (vector form, N'=3..5)
%
% NOTE: All aerodynamic/mass/inertia numbers below are GENERIC
% illustrative values for a small aerodynamically-controlled airframe.
% They are placeholders for you to tune with real data from your
% coursework/lab, not a real weapon design.

clear; clc;
close all force;

modelName = 'Interceptor6DOF';

% Close & delete any previous copy so the script is re-runnable
if bdIsLoaded(modelName)
    close_system(modelName, 0);
end
if exist([modelName '.slx'], 'file')
    delete([modelName '.slx']);
end

new_system(modelName);
open_system(modelName);
set_param(modelName, 'Solver', 'ode45', 'StopTime', '30', ...
    'MaxStep', '0.01', 'RelTol', '1e-6');


% Add a MATLAB Function block with a given script body

function add_matlab_fcn_block(modelName, blockName, position, scriptText)
    blockPath = [modelName '/' blockName];
    add_block('simulink/User-Defined Functions/MATLAB Function', blockPath, ...
        'Position', position);
    rt = sfroot;
    chart = rt.find('-isa', 'Stateflow.EMChart', 'Path', blockPath);
    chart.Script = scriptText;
end


%%  1) TARGET block  -- constant-velocity (non-maneuvering) target

targetScript = sprintf([ ...
'function [Rt, Vt] = fcn(t)\n' ...
'%%#codegen\n' ...
'%% Non-maneuvering target starting 6000 m north, 3000 m altitude,\n' ...
'%% closing at 250 m/s toward the missile launch point.\n' ...
'R0 = [5000; 500; -3000];   %% NED: [North; East; Down] (Down negative = up)\n' ...
'V0 = [-250; 10; 20];         %% constant velocity, m/s\n' ...
'Rt = R0 + V0*t;\n' ...
'Vt = V0;\n' ...
'end']);

add_matlab_fcn_block(modelName, 'Target', [40 40 160 100], targetScript);

clockBlk = [modelName '/Clock'];
add_block('simulink/Sources/Clock', clockBlk, 'Position', [40 140 60 160]);


%%  2) MISSILE_EOM block -- 12-state nonlinear equations of motion

eomScript = sprintf([ ...
'function xdot = fcn(x, F, M)\n' ...
'%%#codegen\n' ...
'%% Generic small-interceptor mass properties (tune with real data)\n' ...
'm    = 120;      %% kg\n' ...
'Ixx  = 8;         %% kg*m^2 (roll)\n' ...
'Iyy  = 55;        %% kg*m^2 (pitch)\n' ...
'Izz  = 55;        %% kg*m^2 (yaw)\n' ...
'g0   = 9.81;\n\n' ...
'u=x(1); v=x(2); w=x(3);\n' ...
'p=x(4); q=x(5); r=x(6);\n' ...
'phi=x(7); theta=x(8); psi=x(9);\n\n' ...
'Fx=F(1); Fy=F(2); Fz=F(3);\n' ...
'Mx=M(1); My=M(2); Mz=M(3);\n\n' ...
'%% gravity resolved into body axes\n' ...
'gx = -g0*sin(theta);\n' ...
'gy =  g0*cos(theta)*sin(phi);\n' ...
'gz =  g0*cos(theta)*cos(phi);\n\n' ...
'udot = Fx/m + gx - q*w + r*v;\n' ...
'vdot = Fy/m + gy - r*u + p*w;\n' ...
'wdot = Fz/m + gz - p*v + q*u;\n\n' ...
'pdot = ((Iyy-Izz)/Ixx)*q*r + Mx/Ixx;\n' ...
'qdot = ((Izz-Ixx)/Iyy)*p*r + My/Iyy;\n' ...
'rdot = ((Ixx-Iyy)/Izz)*p*q + Mz/Izz;\n\n' ...
'phidot   = p + tan(theta)*(q*sin(phi)+r*cos(phi));\n' ...
'thetadot = q*cos(phi) - r*sin(phi);\n' ...
'psidot   = (q*sin(phi)+r*cos(phi))/cos(theta);\n\n' ...
'cphi=cos(phi); sphi=sin(phi);\n' ...
'cth=cos(theta); sth=sin(theta);\n' ...
'cpsi=cos(psi); spsi=sin(psi);\n' ...
'DCM = [cth*cpsi, sphi*sth*cpsi-cphi*spsi, cphi*sth*cpsi+sphi*spsi;\n' ...
'       cth*spsi, sphi*sth*spsi+cphi*cpsi, cphi*sth*spsi-sphi*cpsi;\n' ...
'       -sth,      sphi*cth,                cphi*cth];\n' ...
'posdot = DCM*[u;v;w];\n\n' ...
'xdot = [udot;vdot;wdot;pdot;qdot;rdot;phidot;thetadot;psidot;posdot];\n' ...
'end']);

add_matlab_fcn_block(modelName, 'Missile_EOM', [560 260 700 340], eomScript);

% Vector integrator for the 12 states
intBlk = [modelName '/State_Integrator'];
add_block('simulink/Continuous/Integrator', intBlk, ...
    'Position', [760 260 800 340]);
% Initial state: launch at origin, level, pointed North, ~350 m/s forward
x0 = '[350;0;0;0;0;0; 0;15*pi/180;0; 0;0;0]';
set_param(intBlk, 'InitialCondition', x0);


%%  3) MISSILE_NED_STATE -- convert state x into NED position & velocity

nedScript = sprintf([ ...
'function [Rm, Vm] = fcn(x)\n' ...
'%%#codegen\n' ...
'u=x(1); v=x(2); w=x(3);\n' ...
'phi=x(7); theta=x(8); psi=x(9);\n' ...
'cphi=cos(phi); sphi=sin(phi);\n' ...
'cth=cos(theta); sth=sin(theta);\n' ...
'cpsi=cos(psi); spsi=sin(psi);\n' ...
'DCM = [cth*cpsi, sphi*sth*cpsi-cphi*spsi, cphi*sth*cpsi+sphi*spsi;\n' ...
'       cth*spsi, sphi*sth*spsi+cphi*cpsi, cphi*sth*spsi-sphi*cpsi;\n' ...
'       -sth,      sphi*cth,                cphi*cth];\n' ...
'Rm = x(10:12);\n' ...
'Vm = DCM*[u;v;w];\n' ...
'end']);

add_matlab_fcn_block(modelName, 'Missile_NED_State', [860 260 1000 340], nedScript);


%  4) GUIDANCE (True Proportional Navigation + Gravity Comp)

guidScript = sprintf([ ...
'function acmd = fcn(Rt, Vt, Rm, Vm)\n' ...
'%%#codegen\n' ...
'N = 4;                            %% Navigation constant\n' ...
'Rrel = Rt - Rm;\n' ...
'Vrel = Vt - Vm;\n' ...
'r2 = dot(Rrel,Rrel);\n' ...
'if r2 < 1, r2 = 1; end\n' ...
'omega = cross(Rrel, Vrel) / r2;   %% LOS rotation rate vector\n' ...
'Vc = -dot(Rrel,Vrel)/sqrt(r2);    %% Closing velocity\n' ...
'%% True PN + Gravity Compensation (Commanding 1g UP [-Z] to prevent droop)\n' ...
'acmd = N * Vc * cross(omega, Rrel/sqrt(r2)) + [0; 0; -9.81];\n' ...
'end']);

add_matlab_fcn_block(modelName, 'Guidance_PN', [1060 200 1200 280], guidScript);


%%  5) AUTOPILOT (Dynamic Gain Scheduling)

apScript = sprintf([ ...
'function delta = fcn(acmd, x)\n' ...
'%%#codegen\n' ...
'%% Calculate Dynamic Pressure (qbar) for gain scheduling\n' ...
'u=x(1); v=x(2); w=x(3);\n' ...
'Vt = sqrt(u^2+v^2+w^2);\n' ...
'if Vt < 1, Vt = 1; end\n' ...
'rho = 1.225 * exp(x(12)/8500);    %% Air density at current altitude (-Z)\n' ...
'qbar = 0.5 * rho * Vt^2;\n\n' ...
'phi=x(7); theta=x(8); psi=x(9);\n' ...
'cphi=cos(phi); sphi=sin(phi);\n' ...
'cth=cos(theta); sth=sin(theta);\n' ...
'cpsi=cos(psi); spsi=sin(psi);\n' ...
'DCM = [cth*cpsi, sphi*sth*cpsi-cphi*spsi, cphi*sth*cpsi+sphi*spsi;\n' ...
'       cth*spsi, sphi*sth*spsi+cphi*cpsi, cphi*sth*spsi-sphi*cpsi;\n' ...
'       -sth,      sphi*cth,                cphi*cth];\n' ...
'a_body = DCM.''*acmd;              %% NED->body\n\n' ...
'%% Auto-tune Kp using Mass / (22 * Sref) so it tracks perfectly 1-to-1\n' ...
'Kp = 174 / qbar;\n\n' ...
'delta_pitch = Kp * a_body(3);\n' ...
'delta_yaw   = Kp * a_body(2);\n\n' ...
'maxDef = 20*pi/180;\n' ...
'delta_pitch = max(min(delta_pitch, maxDef), -maxDef);\n' ...
'delta_yaw   = max(min(delta_yaw,   maxDef), -maxDef);\n\n' ...
'delta = [delta_pitch; delta_yaw];\n' ...
'end']);

add_matlab_fcn_block(modelName, 'Autopilot', [1060 320 1200 400], apScript);


%%  6) ACTUATORS -- 2nd order fin actuator dynamics (Demux -> 2x TF -> Mux)

demuxBlk = [modelName '/Demux_Delta'];
add_block('simulink/Signal Routing/Demux', demuxBlk, ...
    'Position', [860 380 870 440], 'Outputs', '2');

tfPitchBlk = [modelName '/Actuator_Pitch'];
add_block('simulink/Continuous/Transfer Fcn', tfPitchBlk, ...
    'Position', [910 370 990 400], ...
    'Numerator', '[3600]', 'Denominator', '[1 84 3600]'); % wn=60, zeta=0.7

tfYawBlk = [modelName '/Actuator_Yaw'];
add_block('simulink/Continuous/Transfer Fcn', tfYawBlk, ...
    'Position', [910 410 990 440], ...
    'Numerator', '[3600]', 'Denominator', '[1 84 3600]');

muxActBlk = [modelName '/Mux_Delta_Actual'];
add_block('simulink/Signal Routing/Mux', muxActBlk, ...
    'Position', [1010 380 1020 440], 'Inputs', '2');


%%  7) AERODYNAMICS -- forces & moments from state + fin deflection

aeroScript = sprintf([ ...
'function [F, M, alpha, beta, Vt] = fcn(x, delta)\n' ...
'%%#codegen\n' ...
'%% Generic linear missile aero model + boost/sustain thrust.\n' ...
'u=x(1); v=x(2); w=x(3); q=x(5); r=x(6);\n' ...
'zpos = x(12);\n\n' ...
'Vt = sqrt(u^2+v^2+w^2);\n' ...
'if Vt < 1\n' ...
'    Vt = 1;\n' ...
'end\n' ...
'alpha = atan2(w,u);\n' ...
'beta  = asin(max(min(v/Vt,1),-1));\n\n' ...
'%% simple exponential atmosphere\n' ...
'alt = -zpos;\n' ...
'rho0 = 1.225; H = 8500;\n' ...
'rho = rho0*exp(-alt/H);\n' ...
'qbar = 0.5*rho*Vt^2;\n\n' ...
'Sref = 0.0314;   %% m^2, reference area (~200mm diameter body)\n' ...
'd    = 0.2;      %% m, reference length\n\n' ...
'%% aero coefficients (generic, linear)\n' ...
'CNalpha = 12; CNdelta = 8;\n' ...
'CYbeta  = -12; CYdelta = -8;\n' ...
'Cmalpha = -4;  Cmdelta = -10; Cmq = -200;\n' ...
'Cnbeta  = 4;   Cndelta = 10;  Cnr = -200;\n' ...
'CA0 = 0.3;      %% axial drag coefficient\n\n' ...
'delta_p = delta(1); delta_y = delta(2);\n\n' ...
'CN = CNalpha*alpha + CNdelta*delta_p;\n' ...
'CY = CYbeta*beta   + CYdelta*delta_y;\n' ...
'CA = CA0;\n\n' ...
'Cm = Cmalpha*alpha + Cmdelta*delta_p + Cmq*q*d/(2*Vt);\n' ...
'Cn = Cnbeta*beta   + Cndelta*delta_y + Cnr*r*d/(2*Vt);\n' ...
'Cl = 0;   %% no roll control modeled\n\n' ...
'%% simple boost-sustain thrust profile (illustrative only)\n' ...
'thrust = 400;   %% N, constant sustain thrust along body x-axis\n\n' ...
'Fx = -qbar*Sref*CA + thrust;\n' ...
'Fy =  qbar*Sref*CY;\n' ...
'Fz = -qbar*Sref*CN;\n\n' ...
'Mx = qbar*Sref*d*Cl;\n' ...
'My = qbar*Sref*d*Cm;\n' ...
'Mz = qbar*Sref*d*Cn;\n\n' ...
'F = [Fx;Fy;Fz];\n' ...
'M = [Mx;My;Mz];\n' ...
'end']);

add_matlab_fcn_block(modelName, 'Aerodynamics', [280 260 420 340], aeroScript);


%% 8) SCOPES / LOGGING

% Miss distance
missDistScript = sprintf([ ...
'function miss=fcn(Rt,Rm)\n' ...
'%%#codegen\n' ...
'miss=norm(Rt-Rm);\n' ...
'end']);

add_matlab_fcn_block(modelName,'MissDistance',[1220 180 1320 240],missDistScript);

add_block('simulink/Sinks/Scope',[modelName '/Scope_MissDistance'],...
'Position',[1380 180 1420 210]);

% Target Position
add_block('simulink/Sinks/To Workspace',[modelName '/To_Workspace_Rt'],...
'VariableName','Rt_log',...
'SaveFormat','Structure With Time',...
'Position',[1050 20 1160 50]);

% Missile Position
add_block('simulink/Sinks/To Workspace',[modelName '/To_Workspace_Rm'],...
'VariableName','Rm_log',...
'SaveFormat','Structure With Time',...
'Position',[1050 60 1160 90]);

% Target Velocity
add_block('simulink/Sinks/To Workspace',[modelName '/To_Workspace_Vt'],...
'VariableName','Vt_log',...
'SaveFormat','Structure With Time',...
'Position',[1050 100 1160 130]);

% Missile Velocity
add_block('simulink/Sinks/To Workspace',[modelName '/To_Workspace_Vm'],...
'VariableName','Vm_log',...
'SaveFormat','Structure With Time',...
'Position',[1050 140 1160 170]);

% Interception detector
interceptScript = sprintf([ ...
'function [hit,tHit]=fcn(Rt,Rm,t)\n' ...
'%%#codegen\n' ...
'if norm(Rt-Rm)<=10\n' ...
' hit=1; tHit=t;\n' ...
'else\n' ...
' hit=0; tHit=-1;\n' ...
'end\n' ...
'end']);

add_matlab_fcn_block(modelName,'Interception_Detection',...
[1220 270 1360 330],interceptScript);

add_block('simulink/Sinks/To Workspace',[modelName '/To_Workspace_Hit'],...
'VariableName','Hit_log',...
'SaveFormat','Structure With Time',...
'Position',[1400 270 1510 300]);

add_block('simulink/Sinks/To Workspace',[modelName '/To_Workspace_tHit'],...
'VariableName','tHit_log',...
'SaveFormat','Structure With Time',...
'Position',[1400 320 1510 350]);


% 9) WIRING

add_line(modelName,'Clock/1','Target/1','autorouting','on');

add_line(modelName,'Target/1','Guidance_PN/1','autorouting','on');
add_line(modelName,'Target/2','Guidance_PN/2','autorouting','on');

add_line(modelName,'Target/1','MissDistance/1','autorouting','on');

add_line(modelName,'State_Integrator/1','Missile_NED_State/1','autorouting','on');

add_line(modelName,'Missile_NED_State/1','Guidance_PN/3','autorouting','on');
add_line(modelName,'Missile_NED_State/2','Guidance_PN/4','autorouting','on');

add_line(modelName,'Missile_NED_State/1','MissDistance/2','autorouting','on');

add_line(modelName,'Guidance_PN/1','Autopilot/1','autorouting','on');
add_line(modelName,'State_Integrator/1','Autopilot/2','autorouting','on');

add_line(modelName,'Autopilot/1','Demux_Delta/1','autorouting','on');
add_line(modelName,'Demux_Delta/1','Actuator_Pitch/1','autorouting','on');
add_line(modelName,'Demux_Delta/2','Actuator_Yaw/1','autorouting','on');

add_line(modelName,'Actuator_Pitch/1','Mux_Delta_Actual/1','autorouting','on');
add_line(modelName,'Actuator_Yaw/1','Mux_Delta_Actual/2','autorouting','on');

add_line(modelName,'Mux_Delta_Actual/1','Aerodynamics/2','autorouting','on');
add_line(modelName,'State_Integrator/1','Aerodynamics/1','autorouting','on');

add_line(modelName,'Aerodynamics/1','Missile_EOM/2','autorouting','on');
add_line(modelName,'Aerodynamics/2','Missile_EOM/3','autorouting','on');

add_line(modelName,'State_Integrator/1','Missile_EOM/1','autorouting','on');
add_line(modelName,'Missile_EOM/1','State_Integrator/1','autorouting','on');

add_line(modelName,'MissDistance/1','Scope_MissDistance/1','autorouting','on');

% Logging
add_line(modelName,'Target/1','To_Workspace_Rt/1','autorouting','on');
add_line(modelName,'Missile_NED_State/1','To_Workspace_Rm/1','autorouting','on');
add_line(modelName,'Target/2','To_Workspace_Vt/1','autorouting','on');
add_line(modelName,'Missile_NED_State/2','To_Workspace_Vm/1','autorouting','on');

% Interception
add_line(modelName,'Target/1','Interception_Detection/1','autorouting','on');
add_line(modelName,'Missile_NED_State/1','Interception_Detection/2','autorouting','on');
add_line(modelName,'Clock/1','Interception_Detection/3','autorouting','on');

add_line(modelName,'Interception_Detection/1','To_Workspace_Hit/1','autorouting','on');
add_line(modelName,'Interception_Detection/2','To_Workspace_tHit/1','autorouting','on');


save_system(modelName,[pwd filesep modelName '.slx']);

fprintf('Model built and saved as %s.slx\n',modelName);
fprintf('Run using: sim(''%s'')\n',modelName);
